@startuml
component DataStructure[
  **Data Structures**
  This represents 
  TenenaList, 
  RentRecord, and ExpenseRecord
]
[User Interface] -left- [Input Screen]
[User Interface] -- [Output Screen]
InitializeData -left-> [DB]
[DB] ..> DataStructure: Insert data
[User Interface] - DataStructure
[Input Screen] -up-> GetInput
GetInput .right.> [DB]: Store data
[Output Screen] -> Display
Display .right.> DataStructure
@enduml
