@startuml ben
left to right direction
actor Landlord as L
package "Usecases" {

    usecase Start as "**1. Start the program**\n
    ==
    Summary:Ask user to choose options between\nInsert, Display, and Quit\n"

    usecase Display as "**Display data**\n
    ==
    Summary:\n
    "

    (4. Display Tenant List) as DTL
    (5. Display Rent Record) as DRR
    (6. Display Expense Record) as DER
    (7. Display Annual Summary) as DAS
    
    Display ..>(DTL): "<<include>>"
    Display ..>(DRR): "<<include>>"
    Display ..>(DER): "<<include>>"
    Display ..>(DAS): "<<include>>"

    /'
    DER ..> (Month Date): "<<include>>"
    DER ..> (Budget Category): "<<include>>"
    DER ..> (Payee): "<<include>>"
    DER ..> (Amount): "<<include>>"
    DAS ..> (Display Table): "<<include>>"
    DAS ..> (Display budget): "<<include>>"
    DAS ..> (Display balance): "<<include>>"
    '/

    usecase InsertData as "**Insert data**\n
    ==
    Summary:\n

    "
    (2. Add New Tenant) as ANT
    (3. Input a Rental Payment) as IRP
    InsertData ..> ANT: "<<include>>"
    InsertData ..> IRP: "<<include>>"

    usecase Quit as "**Quit program**\n
    ==
    Summary:\n

    "
}

L -- Start

Start --|> Display
Start --|> InsertData
Start --|> Quit

@enduml
