@startuml ben
left to right direction
actor Landlord as L
package "Usecases" {

    usecase Start as "**1. Start the program**\n
    ==
    Summary:Ask user to choose options between\n
    Insert, Display, and Quit.\n
    Also need to retrieve all data\n
    from DB as the program starts.
    "

    usecase Display as "**Display data**\n
    ==
    Summary:Choose to display between Annual\n
    summary, Expense record, rent record,\n
    and display tenant list.
    "

    (4. Display Tenant List) as DTL
    (5. Display Rent Record) as DRR
    (6. Display Expense Record) as DER
    (7. Display Annual Summary) as DAS
    
    Display ..>(DTL): "<<include>>"
    Display ..>(DRR): "<<include>>"
    Display ..>(DER): "<<include>>"
    Display ..>(DAS): "<<include>>"

    /'
    DER ..> (Month Date): "<<include>>"
    DER ..> (Budget Category): "<<include>>"
    DER ..> (Payee): "<<include>>"
    DER ..> (Amount): "<<include>>"
    DAS ..> (Display Table): "<<include>>"
    DAS ..> (Display budget): "<<include>>"
    DAS ..> (Display balance): "<<include>>"
    '/

    usecase InsertData as "**Insert data**\n
    ==
    Summary:Ask user to choose between\n 
    the options between Input rental payment,\n
    and Add new tenant\n
    "
    (2. Add New Tenant) as ANT
    (3. Input a Rental Payment) as IRP
    InsertData ..> ANT: "<<include>>"
    InsertData ..> IRP: "<<include>>"

    usecase Quit as "**Quit program**\n
    ==
    Summary: Program gets terminated.\n
    All data need to be flushed into DB\n
    as the program gets terminated.
    "
}

L -- Start

Start --|> Display
Start --|> InsertData
Start --|> Quit

@enduml
