@startuml StartProgram

Landlord -> System: Start the program

System->DB:LoadAllData()

return success

System->System: DisplayMenu()

Landlord <- System: Ask user input

alt The user input is valid
  alt if user input = 'd'
    Landlord -> System
    return Go to display
  end
  alt if user input = 'i'
    Landlord -> System
    return Go to insert data
  end
  alt if user input = 'q'
    Landlord -> System
    return Go to quit
  end
else The user input is invalid
  loop 
    Landlord <- System: DisplayMenu()
    Landlord <- System: Ask userinput
  end
end

@enduml
