@startuml AddTenant
actor Landlord
component System
component TenantList

Landlord -> System: 1. Input name\n1.2. Input apartment number
System -up- System: 1.1 Input validation (name)\n1.3 Input validation (name)

System --> TenantList: 1.4 <<create>>\n1.5 Insert a tenant

@enduml